### ISSUE TITLE
Top, Best stories and comments not loading

### ISSUE THREAD

**Issue by tdkl** [nealyoung/HackerFeed#4]
I've been trying to use this app for a while now, but it rarely loads the top stories and comments. I saw it was updated today, but still the same issues. What seems to the problem, the HN API ? edit: My device is an iPhone 5S, iOS 8.3.

**Comment by Shoeboxam** [comment]
I'm experiencing the same problem, but only for comments. iOS 8.3, 5s. Tested with Hackerfeed 1.4.

http://i.imgur.com/XP5Rjy8.jpg

**Comment by nealyoung** [comment]
Unfortunately, it looks like HN has changed their markup again. The parsing library that I'm using already has an issue open (https://github.com/bennyguitar/libHN/issues/35) and should update soon, which will restore functionality without requiring an app update.

**Comment by tdkl** [comment]
Thanks for replying, I'll keep an eye on the parsing library issue then. 

Mind giving your feedback about another issue/feature request I've posted earlier : https://github.com/nealyoung/HackerFeed/issues/3 ?

**Comment by bennyguitar** [comment]
Hey, creator of the library ([libHN](https://github.com/bennyguitar/libHN) this app uses here, and this should be fixed. You might have to restart the app and wait a few seconds for it to load the new configuration, but after that, if the app followed my documentation, it should begin loading comments again. :)

**Comment by nealyoung** [comment]
@bennyguitar Thanks for the update! Comments are appearing for me after an app restart, so I'm closing this issue now.

**Comment by tdkl** [comment]
Yep it works now, thank you very much :]
